<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
	<head>
		<title><?php echo $this->pagetitle; ?></title>
		
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		
		<link rel="stylesheet" type="text/css" href="/public/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="/public/css/bootstrap-theme.min.css">
		<link rel="stylesheet" type="text/css" href="/public/css/bootstrap-modal-bs3patch.css">
		<link rel="stylesheet" type="text/css" href="/public/css/bootstrap-modal.css">
		<link rel="stylesheet" type="text/css" href="/public/css/font-awesome.min.css">
		<link rel="stylesheet" type="text/css" href="/public/css/stylesheet.css">
		
		<script src="/public/js/jquery-2.1.0.min.js"></script>
		<script src="/public/js/bootstrap.min.js"></script>
		<script src="/public/js/bootstrap-modal.js"></script>
		<script src="/public/js/bootstrap-modalmanager.js"></script>
		<!-- <script src="/public/js/bootstrap-vertical-fix.js"></script> -->
		
		<script>
		</script>
	</head>
	<body>