<div class="container">
	<div class="row">
		
		<!-- NAVIGATION BAR TOP -->
		<nav class="navbar navbar-default" role="navigation">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">Browsergame</a>
			</div>
			
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      		<ul class="nav navbar-nav">
	        		<li class="active"><a href="<?php echo URI::GenerateUrl('home'); ?>"><?php Get('nav_home'); ?></a></li>
	        		<li class=""><a href="#"><?php Get('nav_forums'); ?></a></li>
	        		<li class=""><a href="#"><?php Get('nav_ticketsystem'); ?></a></li>
	        		<li class=""><a href="<?php echo URI::GenerateUrl('media'); ?>"><?php Get('nav_media'); ?></a></li>
	        		<li class=""><a href="<?php echo URI::GenerateUrl('about'); ?>"><?php Get('nav_about_us'); ?></a></li>
	        	</ul>
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php Get('lbl_language'); ?> <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<?php
							$lang	= Language::GetLanguage();
							$de		= '';
							$en		= '';
							switch($lang) {
								case 'de':
									$de	= 'active';
									break;
								case 'en':
									$en	= 'active';
									break;
							}
							?>
							<li class="<?php echo $de; ?>"><a href="#"><img src="/img/flags/shiny/24/germany.png" /> <?php Get('lang_german'); ?></a></li>
							<li class="<?php echo $en; ?>"><a href="#"><img src="/img/flags/shiny/24/united-kingdom.png" /> <?php Get('lang_english'); ?></a></li>
						</ul>
					</li>
				</ul>
	        </div>		
		</nav>
		
		<div class="col-sm-4 well">
			<fieldset>
				<legend>Login</legend>
				<form class="form-horizontal" role="form" action="<?php echo URI::GenerateUrl('login'); ?>" method="post">
					<div class="form-group">
						<label for="server" class="col-sm-4 control-label"><?php Get('lbl_server'); ?></label>
						<div class="col-sm-8">
							<select class="form-control" id="server" name="server">
								<option value="1">NAME #1</option>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label for="login_username" class="col-sm-4 control-label"><?php Get('lbl_username'); ?></label>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="login_username" name="login_username">
						</div>
					</div>
					<div class="form-group">
						<label for="login_password" class="col-sm-4 control-label"><?php Get('lbl_password'); ?></label>
						<div class="col-sm-8">
							<input type="password" class="form-control" id="login_password" name="login_password">
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-12">
							<button type="submit" class="btn btn-success btn-block"><?php Get('lbl_login'); ?></button>
							<button type="button" class="btn btn-danger btn-block" href="#registration_form_modal" data-toggle="modal"><?php Get('lbl_register'); ?></button>
						</div>
					</div>
				</form>
			</fieldset>			
		</div>
		<div class="col-sm-offset-1 col-sm-7 well">
			<legend><?php Get('lbl_news'); ?><span class="pull-right">07.02.2014</span></legend>
			<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
		</div>
	</div>
</div>

<script>
	$(document).ready(function() {
		var bool_username	= false;
		var bool_mail		= false;
		var bool_password	= false;
		var bool_tou		= false;
		
		// Reset registration form
		$('#btn_cancel_registration').click(function() {
			$('#registration_form')[0].reset();
			removeClasses('#register_username input', '#state_username');
			removeClasses('#register_mail input', '#state_mail');
			removeClasses('#register_password input', '#state_password');
			removeClasses('#register_password_confirmation input', '#state_password_confirmation');
		});

		// Remove every class from element
		function removeClasses(sourceElement, targetElement) {
			$(sourceElement).parent().parent().removeClass('has-error');
			$(sourceElement).parent().parent().removeClass('has-success');
			$(sourceElement).parent().parent().find('p').remove();
			$(targetElement).html('<i class="fa fa-question fa-lg"></i>');
		}

		// Show error
		function ShowError(sourceElement, targetElement, errorMsg) {
			$(sourceElement).parent().parent().addClass('has-error');
			$(sourceElement).parent().parent().append('<p class="col-sm-offset-5">' + errorMsg + '</p>');
			$(targetElement).html('<i class="fa fa-times fa-lg"></i>');
		}

		// Show success
		function ShowSuccess(sourceElement, targetElement) {
			$(sourceElement).parent().parent().addClass('has-success');
			$(targetElement).html('<i class="fa fa-check fa-lg"></i>');
		}

		// Enable registration button
		function CheckRegistrationInformations() {
			if(bool_username && bool_mail && bool_password && bool_tou) {
				$('#btn_send_registration').removeAttr('disabled');
			} else {
				$('#btn_send_registration').attr('disabled', 'disabled');
			}
		}

		// Check username input
		$('#register_username input').change(function() {
			var allowed_chars	= /^([a-zA-Z0-9_])*$/;
			var username		= $(this).val();

			removeClasses(this, '#state_username');
			bool_username	= false;

			if(username != '') {		
				if(username.length < 4) {
					ShowError(this, '#state_username', '<?php Get('exc_at_least_x_chars', array(4)); ?>');
				}
				else if(!allowed_chars.test(username)) {
					ShowError(this, '#state_username', '<?php Get('exc_not_allowed_chars', array('A-Z', '0-9', '_')); ?>');
				}
				else {
					var datas	= {'username': username};
					
					$.ajax({
						url:	'<?php echo URI::GenerateUrl('home', 'checkuser'); ?>',
						type:	'post',
						data:	datas,
						async:	false,
						success: function(result) {
							if(result == '1') {
								ShowSuccess($('#register_username input'), '#state_username');
								bool_username	= true;
							} else {
								ShowError($('#register_username input'), '#state_username', '<?php Get('exc_username_already_taken'); ?>');
							}
						}
					});
				}
			}
			CheckRegistrationInformations();
		});

		// Check mail input
		$('#register_mail input').change(function() {
			var pattern	= /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
			var mail	= $(this).val();
			
			removeClasses(this, '#state_mail');
			bool_mail	= false;
			
			if(mail != '') {
				if(!pattern.test(mail)) {
					ShowError(this, '#state_mail', '<?php Get('exc_mail_not_valid'); ?>');
				} else {
					var datas	= {'mail': mail};
					
					$.ajax({
						url:	'<?php echo URI::GenerateUrl('home', 'checkmail'); ?>',
						type:	'post',
						data:	datas,
						async:	false,
						success: function(result) {
							if(result == '1') {
								ShowSuccess($('#register_mail input'), '#state_mail');
								bool_mail	= true;
							} else {
								ShowError($('#register_mail input'), '#state_mail', '<?php Get('exc_mail_already_taken'); ?>');
							}
						}
					});
				}
			}
			CheckRegistrationInformations();
		});

		// Check password input
		$('#register_password input').change(function() {
			var password	= $(this).val();

			removeClasses(this, '#state_password');
			bool_password	= false;

			if(password != '') {
				if(password.length < 5) {
					ShowError(this, '#state_password', '<?php Get('exc_at_least_x_chars', array(5)); ?>');
				} else {
					ShowSuccess(this, '#state_password');
					bool_password	= true;
				}
			}
			CheckRegistrationInformations();
		});

		// Check terms of use checkbox
		$('#register_tou input').click(function() {
			if($(this).is(':checked')) {
				bool_tou	= true;
			} else {
				bool_tou	= false;
			}
			CheckRegistrationInformations();
		});

		// Process registration inputs
		$('#btn_send_registration').click(function() {
			var form_data	= {
					'username':	$('#register_username input').val(),
					'mail':		$('#register_mail input').val(),
					'password':	$('#register_password input').val(),
					'tou':		$('#register_tou input').val()
			}

			$.ajax({
				url:		'<?php echo URI::GenerateUrl('home', 'process'); ?>',
				type:		'post',
				async:		false,
				data:		form_data,
				success:	function(result) {
					console.log(result);
					if(result == '1') {
						$('#registration_success_mail').html('<?php Get("msg_mail_send_to"); ?>');
						$('#registration_form_modal').modal('hide');
						$('#registration_successfull').modal('show');

						$('#registration_form')[0].reset();
						removeClasses('#register_username input', '#state_username');
						removeClasses('#register_mail input', '#state_mail');
						removeClasses('#register_password input', '#state_password');
						removeClasses('#register_password_confirmation input', '#state_password_confirmation');
					} else {
						$('#registration_failed').modal('show');
					}
				}				
			});
		});
		 
	});
</script>

<!-- MODAL REGISTRATION FORM -->
<div class="modal fade" id="registration_form_modal" tabindex="-1" data-backdrop="static">
	<div class="modal-header">
		<h4 class="modal-title" id="registration_form_modal_label"><?php Get('lbl_create_new_account'); ?></h4>
	</div>
	<div class="modal-body">
		<form class="form-horizontal" role="form" id="registration_form">
			<div class="form-group">
				<label for="register_username" class="col-sm-5 control-label"><?php Get('lbl_username'); ?></label>
				<div class="col-sm-7 input-group" id="register_username">
					<input type="text" class="form-control" maxlength="20" name="register_username">
					<span class="input-group-addon" id="state_username"><i class="fa fa-question fa-lg"></i></span>
				</div>
			</div>
			<div class="form-group">
				<label for="register_email" class="col-sm-5 control-label"><?php Get('lbl_mail'); ?></label>
				<div class="col-sm-7 input-group" id="register_mail">
					<input type="text" class="form-control" name="register_mail">
					<span class="input-group-addon" id="state_mail"><i class="fa fa-question fa-lg"></i></span>
				</div>
			</div>
			<div class="form-group">
				<label for="register_password" class="col-sm-5 control-label"><?php Get('lbl_password'); ?></label>
				<div class="col-sm-7 input-group" id="register_password">
					<input type="password" class="form-control" name="register_password">
					<span class="input-group-addon" id="state_password"><i class="fa fa-question fa-lg"></i></span>
				</div>
			</div>
			<div class="checkbox col-sm-offset-5" id="register_tou">
				<label>
					<input type="checkbox"> <?php Get('lbl_accept_tou'); ?> <a href="#"><?php Get('lbl_tou_short'); ?></a>
				</label>
			</div>
		</form>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-danger" id="btn_cancel_registration" data-dismiss="modal"><?php Get('lbl_cancel'); ?></button>
		<button type="button" class="btn btn-success" id="btn_send_registration" disabled="disabled"><?php Get('lbl_register'); ?></button>
	</div>
</div>

<!-- MODAL REGISTRATION SUCCESS -->
<div class="modal fade" id="registration_successfull" tabindex="-1" data-backdrop="static">
	<div class="modal-header">
		<h4 class="modal-title" id="registration_success_modal_label"><i class="fa fa-check fa-lg text-success"></i> <?php Get('lbl_registration_successfull'); ?></h4>
	</div>
	<div class="modal-body">
		<p id="registration_success_mail"></p>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-success" id="btn_cancel_registration" data-dismiss="modal"><?php Get('lbl_close'); ?></button>
	</div>
</div>

<!-- MODAL REGISTRATION FAILED -->
<div class="modal fade" id="registration_failed" tabindex="-1" data-backdrop="static">
	<div class="modal-header">
		<h4 class="modal-title" id="registration_failed_modal_label"><i class="fa fa-warning fa-lg text-danger"></i> <?php Get('lbl_registration_failed'); ?></h4>
	</div>
	<div class="modal-body">
		<p><?php Get('msg_registration_failure'); ?></p>
		<p><?php Get('msg_pls_try_again_later'); ?></p>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-danger" data-dismiss="modal"><?php Get('lbl_close'); ?></button>
	</div>
</div>