<div class="container">
	<div class="row">
	<nav class="navbar navbar-default" role="navigation">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Browsergame</a>
		</div>
		
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      		<ul class="nav navbar-nav">
        		<li class="active"><a href="/<?php echo Language::GetLanguage(); ?>/home"><?php Get('nav_home'); ?></a></li>
        		<li class=""><a href="#"><?php Get('nav_forums'); ?></a></li>
        		<li class=""><a href="#"><?php Get('nav_ticketsystem'); ?></a></li>
        		<li class=""><a href="/<?php echo Language::GetLanguage(); ?>/media"><?php Get('nav_media'); ?></a></li>
        		<li class=""><a href="/<?php echo Language::GetLanguage(); ?>/about"><?php Get('nav_about_us'); ?></a></li>
        	</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php Get('lbl_language'); ?> <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<?php
						$lang	= Language::GetLanguage();
						$de		= '';
						$en		= '';
						switch($lang) {
							case 'de':
								$de	= 'active';
								break;
							case 'en':
								$en	= 'active';
								break;
						}
						?>
						<li class="<?php echo $de; ?>"><a href="#"><img src="/img/flags/shiny/24/germany.png" /> <?php Get('lang_german'); ?></a></li>
						<li class="<?php echo $en; ?>"><a href="#"><img src="/img/flags/shiny/24/united-kingdom.png" /> <?php Get('lang_english'); ?></a></li>
					</ul>
				</li>
			</ul>
        </div>		
	</nav>
		<div class="col-md-4 well">
			<fieldset>
				<legend>Login</legend>
				<form class="form-horizontal" role="form" action="" method="post">
					<div class="form-group">
						<label for="server" class="col-sm-4 control-label">Welt</label>
						<div class="col-sm-8">
							<select class="form-control" id="server">
								<option>Server 1</option>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label for="login_username" class="col-sm-4 control-label"><?php Get('lbl_username'); ?></label>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="login_username" placeholder="<?php Get('lbl_username'); ?>">
						</div>
					</div>
					<div class="form-group">
						<label for="login_password" class="col-sm-4 control-label"><?php Get('lbl_password'); ?></label>
						<div class="col-sm-8">
							<input type="password" class="form-control" id="login_password" placeholder="<?php Get('lbl_password'); ?>">
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-12">
							<button type="submit" class="btn btn-success btn-block"><?php Get('lbl_login'); ?></button>
							<button type="button" class="btn btn-danger btn-block"><?php Get('lbl_register'); ?></button>
						</div>
					</div>
				</form>
			</fieldset>
		</div>
		<div class="col-md-offset-1 col-md-7 well">
			<legend><?php Get('lbl_news'); ?><span class="pull-right">07.02.2014</span></legend>
			<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
		</div>
		<div class="footer"></div>
	</div>
</div>